name: ping-command
on:
  repository_dispatch:
    types: [ping-command]
jobs:
  helloWorld:
    runs-on: ubuntu-latest
    steps:
     - name: Update comment
       uses: peter-evans/create-or-update-comment@41f3207a84f33bd70388036109082784d059dcaa
       with:
         token: ${{ secrets.PA_TOKEN }}
         repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
         comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
         body: |
           >pong ${{ github.event.client_payload.slash_command.args.all }}
         reactions: hooray


